### ISSUE TITLE
The Component Build Maintainance Costs Runtime vs Build Time Evaluation Paradoxon

### ISSUE THREAD

**Issue by frank-dspeed** [stealify/stealify#19]
# The Component Build Maintainance Costs Runtime vs Build Time Evaluation Paradoxon
I have choosen a Complex name that makes less sense and still makes sense to even show the problem to name that.

## Quick Note for Typescript Users
You do not need to Read this even if your mentioned here. Save Your time and Headache. 

## Current Situations
- Build/Run (The Build can in fact also be seen as Run) as It is a Application Specific step that executes so we can say it is Loading see: https://docs.google.com/presentation/d/1PlQEjS5xyJA-0GY8mjB4wr-pLyzFtdMRfhXczJJ2wic/edit#slide=id.g388aa7220e_2_46
  - Then we cache most time the final result (binary) 
  - We Code Software to auto cache the build steps that adds extra cost of n * n to the build as such tools need to be generic enough
  - Generic Tools Produce Generic Problems. 

- [ ] TypeScript hits walls of generic support fundamental. https://github.com/microsoft/TypeScript/issues/50152
- [ ] NodeJS hits walls of Cross Platform Build Maintainance Costs. 
- [ ] Fuchsia and Chromium do push the wall (CSA, Component Manager FIDL, TQ, LLVM Patches) to name a few
 
This Pushes lead to problems in sub Projects that can not follow up because they got not the Human Resources with the right Hardskill level eg: 20 Years of c++ coding in a high volatile Corp Environment like Google. In other fortune 500 eg Microsoft the Philosophies are different and They are working with a total different overall Mind Set. Google for example has no problem to build and throw away if it is not what it should be. Microsoft would reuse and keep it living for ever and longer see Windows 98 still used on Real Hardware that even is placed in Public Environments also Governments. 

Also every Maintainer of a Module or Extension for this systems has a Hard Time.

## Solutions
Standard for Cross Platform Component Low Level Hardcoded Performant Interfaces are needed. That leads to Problems where solutions exist that we could apply to all Projects in general.

Such a Solution would Include a Binary Format we agree on something like the capnproto implementation which is in fact what Fuchsia uses for FIDL => Server, Client.

Why do i name this FIDL here? It is in Fact a IR Build Result it overlaps with Software like GN.

Overall to make the conclusion Short we got a Big Software Stack that Comes in diffrent Distribution Flavors but still to be Honest we all share the Same Stack and we need Inter Project Communication to bring that to the next Level. 

Now you can ask why do i name Typescript here as it Looks like that is a Consumer Only but i guess it is not it is a Whole own Engine the fact that it is based on the Chromium Powered NodeJS Stack does not matter much also Electron is a Language it self. 

Typescript needs to run on diffrent Engines and needs fundamental redesign as it Self Variates dependend on the Engine Implementation it gets a Own Language that has Diffrent Flavors dependendent on the Resolve Algorythm.

So Typescript needs also a universal binary Interface into the runtime to do its job. Most best Would be to Implement it on the Parser Level Inside v8 that would be equal to the graalvm. Which are the both most used engines that Interop with it and run it. 

The Problem that Typescript as a Producer Maintainer has is that they can not Maintain that in a Compose able way. without Rebuilding the Whole Stack as they need to modify v8. 

So again we come to the Point that we need to agree on a Interface Between Chromium & Fuchsia & NodeJS into v8 as also Typescript the good news is we are creating that interface already the bad is no one is aware of each other Maybe only me is tracking all this Cross Domain Projects i am not sure.

## Roadmap
The Following Roadmap Explains why and how we get the Interface that we can Agree on! As it gets Implemented already.
FuchsiaOS can be seen as a v8 like OS Implementation in fact it shares many many core concepts like Streams Promises and Channels as also async execution and event handler driven design patterns, They use a Concept called FIDL a Lang that produces a before bespoken IR Result which can be used to generate code for all Platforms. (Build Cache that can get turned into directly used clients) NodeJS Should use exactly such clients. to send Transport Agnostic Messages in Binary Typed Form (Protocol) i summon CapNProto for that but FIDL as a sub set of that would be already enough to start capnproto and fidle are exchange able fidl is only a small subset of capnprotos concepts with some additional tooling.

So The Fuchsia NodeJS Integration can later get used as NodeJS Foundation it self as it allows to create binary modules that use fileHandels or other transport to interop they are not required to be written in the same Language to Call each other in a performant way. Combined with v8's core ability as a code optimizer and Scheduler we can Improve the Build of the Consumers a lot CSA has proven that via reusing v8's own TurboFan Compiler to create its own ASM. Now Chromium NodeJS and Fuchsia can reuse v8 + TurboFan and the Fuchsia Component System to build more stable Software. 

- [ ] Fuchsia NodeJS and Chromium Integration leads to v8 modification and NodeJS Modification. 
  - [ ] Fuchsia NodeJS Integration patching nodejs adding new platform 
  - [ ] chromium/v8/node-ci adaptiv GN Build for NodeJS
  - [ ] chromium/v8 Patches for fuchsia and nodejs 

What changes do we expect? 
- Deprecating own meta build system  as Main Concept to create Software that Interfaces NodeJS , Chromium or V8 it Self.
  - v8 already deprecated it
  - chromium did deprecated it 
  - NodeJS does depend on it and can be sayed that it switched to GN in all Relvant Projects that depend on NodeJS (Electron&Chromium/v8) Interristing is that Chromium v8 maintains a own NodeJS build to make sure that NodeJS will work with v8 and to handle incompat upfront. 
  - We can Create a Golden Series of Platform Indipendent Components that use the before bespoken Binary InterOp Transport Agnostic so OS Indipendent and this way finally get shareable reuseable Components for the following Projects
  - NodeJS
  - Chromium
  - v8
  - Electron
  - Typescript
  - NWJS
  - CEF Related Projects.

Finaly the TypeScript Part is to integrate directly into v8 which is the Part that all Projects share that Executes typescript. There where experiments where Strict Typing got added to v8 already we got good results from that Experiment while there where edge cases. 

Anyway it showed that Typescript integrated into v8 would be the most clever as it needs less roundtrips and saves us from Errors with our new nativ component model maybe as it offers to expose a universal facade via .d.ts for binary modules that are not written in JS.

So a Part of Typescript should get Merged into v8 without its resolve stuff and all that like v8 TypeScript would be not in the Position to Handle Resolve and Load of Files. 

We got with a capnproto interface to v8::Isolate a good connection endpoint as bultins get also inited on v8::Isolate::start once

We Will Implement the capnproto interface into v8 via a own v8 Builder that Hooks into all the indipenden Build System parts till they get it self a capnproto interface Then v8 would get used via a v8 compositor (Component Manager) that is able to load capnproto capable extensions
