### ISSUE TITLE
Release: v0.0.1-pre0 - Build first stealify minimal runtime v8 based. v0.0.1-pre0

### ISSUE THREAD

**Issue by frank-dspeed** [stealify/stealify#29]
Build first stealify minimal runtime v8 based. v0.0.1-pre0

## Goals
- [x] use stealifys minimal build system to build stealify as a runtime that can build and execute/run it self. 
- [x] use stealify ecosystem and module linker. 

## What should go into the first build
- [x] stealify executes js and offers repl component-just
- [ ] should expose core concepts Tasks Streams Schedulers Components on globalThis as builtin modules
- [ ] shoud be able to implement a component-manager.
