### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by frank-dspeed** [stealify/stealify#43]
- [ ] Move all issues to the correct places
  - [ ] Stealify Lang
  - [ ] component-manager // Networking and everything else is part of this.
  - [ ] editor
  - [ ] multimedia
  - [ ] b8g engine
  - [ ] direktspeed awsome os and quaternion sdk
- [ ] Create Boot Media Tool
- [ ] Create Web Installer (FileSystem API) 
  - [ ] Implement the ~/.tasks/installer support for stealify systems 
    - [ ] tar stream 
- [ ] Create Web Gui Components set and tools as also helpers.
  - [ ] Window
  - [ ] Field
  - [ ] WindowDecorations
  - [ ] Themes
  - [ ]  ......
- [ ] Improve the build processes.
- [ ] Render vscode in Web Gui including vfs support 
  - [ ] Web Gui Backends 
    - [ ] broiwser
    - [ ] nodejs
    - [ ] stealify
    - [ ] extension
- [ ] Refine the core Stream Implementations for Tasks/Components 
- [ ] Refine hyperapp to work more like TagHTML 
- [ ] Refine the Minimal Bootable Linux 
  - [ ] Refine the x86 posix wasm vm 
- [ ] Refine the editor base it on the Web Gui
- [ ] Refine the webplatform builds
